apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: default
spec:
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["curl", "-k", "https://192.168.49.2:8443/api/v1/namespaces/default/pods"]
  restartPolicy: Always
