apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: default
spec:
  serviceAccountName: default
  initContainers:
  - name: get-token
    image: bitnami/kubectl
    command: ["sh", "-c", "kubectl create token default > /tmp/token"]
  containers:
  - name: curl-container
    image: curlimages/curl
    command:
      - "sh"
      - "-c"
      - "curl -k -H 'Authorization: Bearer $(cat /tmp/token)' https://kubernetes.default.svc/api/v1/namespaces/default/pods"
  restartPolicy: Never