apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: default
spec:
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["sleep", "infinity"]
  restartPolicy: Always
