apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-1
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: service-account-1
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: default
spec:
  serviceAccountName: service-account-1
  containers:
  - name: curl-container
    image: curlimages/curl
    command:
    - "sh"
    - "-c"
    - >
      curl -k https://kubernetes.default.svc/api/v1/namespaces/default/pods --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
